# Generated by Django 5.0.7 on 2024-12-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='ordenes_venta',
            field=models.ManyToManyField(blank=True, to='ventas.ordendeventa'),
        ),
    ]
